deployment:
  tasks:
    - export DEPLOYPATH=/home/nowmbbms/public_html/n
    - |
      for dir in .vscode assets css fonts img js; do
        /bin/cp -R $dir $DEPLOYPATH
      done
    - /bin/cp index.html $DEPLOYPATH
