deployment:
  tasks:
    - export DEPLOYPATH=/home/nowmbbms/public_html/n
    - |
      for dir in .vscode assets css fonts img js; do
        if ! /bin/cp -R $dir $DEPLOYPATH; then
          echo "Error deploying $dir"
          exit 1
        fi
      done
    - if ! /bin/cp index.html $DEPLOYPATH; then
        echo "Error deploying index.html"
        exit 1
      fi
